alter table gps.checksums comment '校验数据表';
alter table gps.city comment '城市';
alter table gps.d_acc_judge comment '行政法官';
alter table gps.d_alarm_process_rec comment '报警过程记录';
alter table gps.d_alarm_process_result comment '报警处理结果';
alter table gps.d_alarm_process_temp comment '报警过程温度';
alter table gps.d_alarm_track_mark comment '报警轨迹标记';
alter table gps.d_app_business comment '应用业务';
alter table gps.d_app_image comment '应用图片';
alter table gps.d_app_image_config comment '应用图像配置';
alter table gps.d_app_image_delete comment '应用图像删除';
alter table gps.d_app_image_rule comment '应用图像规则';
alter table gps.d_app_token comment '应用令牌';
alter table gps.d_app_token_vehicle comment '应用令牌车辆';
alter table gps.d_auth comment '授权';
alter table gps.d_auto_classify_config comment '自动分类配置';
alter table gps.d_basestation_track comment '基站轨道';
alter table gps.d_check_active_log comment '检查活动日志';
alter table gps.d_check_app_active_log comment '检查应用活动日志';
alter table gps.d_class comment '班级';
alter table gps.d_confirm_payment comment '确认付款';
alter table gps.d_cust_alarm_stat_daily comment '每日闹钟';
alter table gps.d_cust_dev_activate_stat_daily comment '每天激活 ';
alter table gps.d_cust_dev_activate_stat_monthly comment '每月激活 ';
alter table gps.d_cust_dev_activate_stat_monthly2 comment '每月激活 ';
alter table gps.d_cust_dev_active_stat_daily comment '活跃每日';
alter table gps.d_cust_dev_active_stat_monthly comment '活跃 每月';
alter table gps.d_cust_dev_active_stat_monthly2 comment '活跃每月';
alter table gps.d_customer_info comment '顾客信息';
alter table gps.d_daily_record comment '日志';
alter table gps.d_daily_record_201603 comment '每日记录 201603';
alter table gps.d_daoqiang_mileage_stat comment '道强里程统计';
alter table gps.d_daoqiang_mileage_stat_his comment '道强里程站';
alter table gps.d_daoqiang_user comment '道强用户';
alter table gps.d_ddhd_user_grade comment 'ddh 用户等级';
alter table gps.d_device_activate_detail comment '设备激活详情';
alter table gps.d_device_activate_detail_0118 comment '设备激活详情 0118';
alter table gps.d_device_activate_detail_202101_04 comment '设备激活详情 202101 04';
alter table gps.d_device_activate_detail_bak comment '设备激活详细信息';
alter table gps.d_device_activate_detail_settle comment '设备激活细节解决';
alter table gps.d_device_active_detail comment '设备活动详情';
alter table gps.d_device_alarm_detail comment '设备报警详情';
alter table gps.d_device_delivery_detail comment '设备交付细节';
alter table gps.d_device_distance_stat comment '设备距离统计';
alter table gps.d_device_freq comment '设备频率';
alter table gps.d_device_freq_yang comment '设备频率阳';
alter table gps.d_device_import_log comment '设备导入日志';
alter table gps.d_device_import_log_detail comment '设备导入日志详细信息';
alter table gps.d_device_login comment '设备登录';
alter table gps.d_device_login_tmp comment '设备登录时间';
alter table gps.d_device_offline_ratio comment '设备离线率';
alter table gps.d_device_operate_log comment '设备操作日志';
alter table gps.d_device_power comment '设备电源';
alter table gps.d_device_power_temp comment '设备电源温度';
alter table gps.d_device_separate_alarm comment '设备单独报警';
alter table gps.d_device_status comment '设备状态';
alter table gps.d_didi_ensure_plan_temp comment '滴滴确保计划温度';
alter table gps.d_dispatch_detail_info comment '发货详细信息';
alter table gps.d_dispatch_sn_list_info comment '调度 sn lis 信息';
alter table gps.d_distributor_info comment '经销商信息';
alter table gps.d_electric_fence comment '电围栏';
alter table gps.d_electric_fence_alarm comment '电子围栏报警器';
alter table gps.d_electric_fence_alarm_temp comment '电围栏报警温度';
alter table gps.d_electric_fence_sns comment '电围栏sns';
alter table gps.d_function comment '功能';
alter table gps.d_fund_account comment '有趣的帐户';
alter table gps.d_gh_devicetime comment ' gh 设备时间';
alter table gps.d_gps_config comment '全球定位系统配置';
alter table gps.d_gps_rt_track comment 'gps r 轨道';
alter table gps.d_group comment '团体';
alter table gps.d_guanghui_mileage_stat comment '广汇里程统计';
alter table gps.d_hgd_broker comment '汞经纪人';
alter table gps.d_hgd_sms comment '汞短信';
alter table gps.d_home_address comment '家庭地址';
alter table gps.d_homeoffset_alarm comment '离家警报';
alter table gps.d_installation_master_info comment '安装主信息';
alter table gps.d_insurance_file comment '保险档案';
alter table gps.d_interface_error_log comment '接口错误日志';
alter table gps.d_ivr_alarm_log comment 'ivr报警日志';
alter table gps.d_ivr_alarm_resend comment 'ivr报警重发';
alter table gps.d_ivr_alarm_resend_his comment 'ivr 警报 resen 他的';
alter table gps.d_mb_rt_track comment 'mb 轨道';
alter table gps.d_monitor_track comment '监控轨道';
alter table gps.d_nes_vehicle_device comment 'nes车载设备';
alter table gps.d_resident_alarm comment '常驻警报';
alter table gps.d_resident_alarm_bak comment '常驻报警器';
alter table gps.d_resident_channel comment '常驻频道';
alter table gps.d_resident_custom comment '民俗';
alter table gps.d_resident_custom_bak comment '居民定制面包';
alter table gps.d_resident_cycle comment '驻留周期';
alter table gps.d_role comment '角色';
alter table gps.d_role_function comment '角色功能';
alter table gps.d_role_function_temp comment '角色函数 temp';
alter table gps.d_role_vehicle_detail comment '角色车辆细节';
alter table gps.d_role_vehicle_detail_temp comment '角色车辆细节温度';
alter table gps.d_role_vehicle_group comment '角色车辆组';
alter table gps.d_role_vehicle_group_temp comment '角色车辆组温度';
alter table gps.d_send_config comment '森配置';
alter table gps.d_service comment '服务';
alter table gps.d_service_phone comment '服务电话';
alter table gps.d_set_frequency comment '频率';
alter table gps.d_settle comment '定居';
alter table gps.d_shopzone_info comment '店铺信息';
alter table gps.d_sms_delivery_log comment '短信发送日志';
alter table gps.d_sms_workorder_delivery comment '短信工单交付';
alter table gps.d_special_promise_insurance comment '特别承诺保险';
alter table gps.d_stat_alarm comment '站警';
alter table gps.d_stat_alarm_his comment '斯塔警报他';
alter table gps.d_stock_info comment '股票信息';
alter table gps.d_sub_voltage comment '次电压';
alter table gps.d_task_sent_log comment '任务发送日志';
alter table gps.d_test_drive_shop comment '试驾店';
alter table gps.d_test_drive_shop_route comment '商店路线';
alter table gps.d_track_alarm_rec comment '跟踪报警记录';
alter table gps.d_track_alarm_rec_dailystat comment '跟踪警报记录dailystat';
alter table gps.d_track_alarm_rec_dailystat_tmp comment '跟踪警报记录dailysta tmp';
alter table gps.d_track_alarm_rec_dailystat_tmp6 comment '跟踪警报记录dailysta tmp6';
alter table gps.d_track_alarm_rec_history comment '跟踪报警记录历史';
alter table gps.d_track_alarm_rec_history_temp comment '跟踪报警记录历史温度';
alter table gps.d_track_alarm_rec_temp comment '跟踪报警记录温度';
alter table gps.d_track_alarm_rec_yang comment '跟踪警报rec yang';
alter table gps.d_track_info comment '跟踪信息';
alter table gps.d_track_info_import comment '跟踪信息导入';
alter table gps.d_track_log comment '跟踪日志';
alter table gps.d_use_log comment '使用日志';
alter table gps.d_user comment '用户';
alter table gps.d_user_class_detailed comment '用户类详细';
alter table gps.d_user_group comment '用户组';
alter table gps.d_user_group_detailed comment '用户组详细';
alter table gps.d_user_role comment '用户角色';
alter table gps.d_user_vehicle comment '用户车辆';
alter table gps.d_vehicle comment '车辆';
alter table gps.d_vehicle_brand comment '车辆品牌';
alter table gps.d_vehicle_brand_type comment '车皮类型';
alter table gps.d_vehicle_device comment '车载装置';
alter table gps.d_vehicle_extend_info comment '车辆扩展信息';
alter table gps.d_vehicle_insurance comment '车辆保险';
alter table gps.d_vehicle_log comment '车辆日志';
alter table gps.d_vehicle_poi comment '车辆定位';
alter table gps.d_vehicle_remark comment '车辆备注';
alter table gps.d_vehicle_subuserid_is_0_to_update_null comment '车辆子用户为 0 更新为空';
alter table gps.d_vehicle_workorder comment '车辆工单';
alter table gps.d_vehicle_workorder_cancel comment '车辆工单取消';
alter table gps.d_vehicle_workorder_gh comment '车辆工单 gh';
alter table gps.d_vehicle_workorder_rep comment '车辆工单代表';
alter table gps.d_violation comment '违反';
alter table gps.d_voltage comment '电压';
alter table gps.d_workorder_reassign comment '工单重新分配';
alter table gps.d_workorder_retransmission comment '工单重传';
alter table gps.d_wx_login_user comment 'wx登录用户';
alter table gps.d_xianfeng_mileage_stat comment '咸丰里程统计';
alter table gps.delivery_active_detail comment '交付活动详细信息';
alter table gps.dsns comment 'dsns';
alter table gps.eshield_device_alarm_deal comment 'eshiel设备报警处理';
alter table gps.gps_vehicle_settled comment 'gps车辆落户';
alter table gps.iot_card_excel comment 'io汽车excel';
alter table gps.login_stat_log comment '登录 sta 日志';
alter table gps.province comment '省';
alter table gps.qrtz_blob_triggers comment 'qrtz blob 触发器';
alter table gps.qrtz_calendars comment 'qrtz 日历';
alter table gps.qrtz_cron_triggers comment 'qrtz cron 触发器';
alter table gps.qrtz_fired_triggers comment 'qrtz 触发';
alter table gps.qrtz_job_details comment 'qrz工作详情';
alter table gps.qrtz_job_listeners comment 'qrtz 作业监听器';
alter table gps.qrtz_locks comment 'qrtz 锁';
alter table gps.qrtz_paused_trigger_grps comment 'qrtz 暂停触发 grps';
alter table gps.qrtz_scheduler_state comment 'qrtz 调度器状态';
alter table gps.qrtz_simple_triggers comment 'qrtz 简单触发器';
alter table gps.qrtz_trigger_listeners comment 'qrtz 触发监听器';
alter table gps.qrtz_triggers comment 'qrtz 触发器';
alter table gps.t_device_config comment '设备配置';
alter table gps.t_device_version comment '设备版本';
alter table gps.t_tracker_info comment '跟踪器信息';
alter table gps.wx_share_vehicle comment 'wx共享车辆';
alter table gps.wx_shared_user comment 'wx 分享用户';
alter table gps.wx_user comment 'wx 用户';
ALTER TABLE gps.checksums modify db  char(64)  NOT NULL  COMMENT '数据库';
ALTER TABLE gps.checksums modify tbl  char(64)  NOT NULL  COMMENT '表';
ALTER TABLE gps.checksums modify chunk  int(11)  NOT NULL  COMMENT '块';
ALTER TABLE gps.checksums modify chunk_time  float  NULL  COMMENT '块时间';
ALTER TABLE gps.checksums modify chunk_index  varchar(200)  NULL  COMMENT '块索引';
ALTER TABLE gps.checksums modify lower_boundary  text  NULL  COMMENT '下界';
ALTER TABLE gps.checksums modify upper_boundary  text  NULL  COMMENT '上界';
ALTER TABLE gps.checksums modify this_crc  char(40)  NOT NULL  COMMENT '这个CRC';
ALTER TABLE gps.checksums modify this_cnt  int(11)  NOT NULL  COMMENT '这个cnt';
ALTER TABLE gps.checksums modify master_crc  char(40)  NULL  COMMENT '主CRC';
ALTER TABLE gps.checksums modify master_cnt  int(11)  NULL  COMMENT '主控';
ALTER TABLE gps.checksums modify ts  timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL on update CURRENT_TIMESTAMP COMMENT 'ts';
ALTER TABLE gps.city modify id  int(11)  NOT NULL  COMMENT '主键';
ALTER TABLE gps.city modify Acronym  varchar(40) CHARACTER SET utf8 COLLATE utf8_bin NULL  COMMENT '首字母缩略词';
ALTER TABLE gps.city modify cityName  varchar(40) CHARACTER SET utf8 COLLATE utf8_bin NULL  COMMENT '城市名';
ALTER TABLE gps.city modify ProvinceId  int(11)  NULL  COMMENT '省份编号';
ALTER TABLE gps.city modify ProvinceName  varchar(40) CHARACTER SET utf8 COLLATE utf8_bin NULL  COMMENT '省名';
ALTER TABLE gps.city modify lat  varchar(40) CHARACTER SET utf8 COLLATE utf8_bin NULL  COMMENT '纬度';
ALTER TABLE gps.city modify lng  varchar(40) CHARACTER SET utf8 COLLATE utf8_bin NULL  COMMENT '液化天然气';
ALTER TABLE gps.city modify pinyin  varchar(100)CHARACTER SET utf8 COLLATE utf8_bin  NULL  COMMENT '拼音';
ALTER TABLE gps.d_acc_judge modify id  int(10)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_acc_judge modify sn  varchar(50)  NULL  COMMENT '设备号';
ALTER TABLE gps.d_acc_judge modify createtime  datetime  NULL  COMMENT '创建时间';
ALTER TABLE gps.d_acc_judge modify sttime  datetime  NULL  COMMENT '时间';
ALTER TABLE gps.d_acc_judge modify ettime  datetime  NULL  COMMENT '时间';
ALTER TABLE gps.d_alarm_stat_report modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_alarm_track_mark modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_alarm_track_mark modify updateTime  datetime  NULL  COMMENT '更新时间';
ALTER TABLE gps.d_alarm_track_mark modify createTime  datetime  NULL  COMMENT '创建时间';
ALTER TABLE gps.d_app_business modify leaseId  int(11)   auto_increment COMMENT '租约 主键';
ALTER TABLE gps.d_app_business modify createTime  datetime  NULL  COMMENT '创建时间';
ALTER TABLE gps.d_app_business modify updateTime  datetime  NULL  COMMENT '更新时间';
ALTER TABLE gps.d_app_image modify name  varchar(50)  NULL  COMMENT '姓名';
ALTER TABLE gps.d_app_image_config modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_app_image_config modify createTime  datetime  NULL  COMMENT '创建时间';
ALTER TABLE gps.d_app_image_config modify updateTime  datetime  NULL  COMMENT '更新时间';
ALTER TABLE gps.d_app_image_delete modify name  varchar(50)  NULL  COMMENT '姓名';
ALTER TABLE gps.d_app_image_rule modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_app_image_rule modify createTime  datetime  NULL  COMMENT '创建时间';
ALTER TABLE gps.d_auth modify auId  int(11)   auto_increment COMMENT '好听';
ALTER TABLE gps.d_auth modify val  varchar(20)  NULL  COMMENT '值';
ALTER TABLE gps.d_auth modify createtime  datetime  NULL  COMMENT '创建时间';
ALTER TABLE gps.d_auth modify remark  varchar(100)  NULL  COMMENT '评论';
ALTER TABLE gps.d_basestation_track modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_basestation_track modify updateTime  datetime  NULL  COMMENT '更新时间';
ALTER TABLE gps.d_basestation_track modify createTime  datetime  NULL  COMMENT '创建时间';
ALTER TABLE gps.d_check_app_active_log modify serviceName  varchar(100)  NULL  COMMENT '服务名称';
ALTER TABLE gps.d_check_app_active_log modify installerName  varchar(64)  NULL  COMMENT '安装程序名称';
ALTER TABLE gps.d_check_app_active_log modify installerPhone  varchar(64)  NULL  COMMENT '安装电话';
ALTER TABLE gps.d_check_app_active_log modify createTime  datetime  NULL  COMMENT '创建时间';
ALTER TABLE gps.d_check_app_active_log modify updateTime  datetime  NULL  COMMENT '更新时间';
ALTER TABLE gps.d_command_user modify command  varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NULL  COMMENT '命令';
ALTER TABLE gps.d_confirm_payment modify isSameMonth  varchar(3)  NULL  COMMENT '同月';
ALTER TABLE gps.d_confirm_payment modify voucher  varchar(100)  NOT NULL  COMMENT '代金券';
ALTER TABLE gps.d_confirm_payment modify createTime  varchar(30)  NOT NULL  COMMENT '创建时间';
ALTER TABLE gps.d_cust_alarm_stat_daily modify alarmDay  varchar(10)  NULL  COMMENT '报警日';
ALTER TABLE gps.d_cust_alarm_stat_daily modify alarmCnt  decimal(42,0)  NULL  COMMENT '报警次数';
ALTER TABLE gps.d_cust_dev_activate_stat_daily modify activeDay  varchar(10)  NULL  COMMENT '活跃日';
ALTER TABLE gps.d_cust_dev_activate_stat_daily modify activeCnt  bigint(21) DEFAULT 0 NOT NULL  COMMENT '活动量';
ALTER TABLE gps.d_cust_dev_activate_stat_monthly modify activeMonth  varchar(7)  NULL  COMMENT '活动月';
ALTER TABLE gps.d_cust_dev_activate_stat_monthly modify activeCnt  decimal(42,0)  NULL  COMMENT '活动量';
ALTER TABLE gps.d_cust_dev_activate_stat_monthly2 modify activeMonth  varchar(7)  NULL  COMMENT '活动月';
ALTER TABLE gps.d_cust_dev_activate_stat_monthly2 modify activeCnt  bigint(21) DEFAULT 0 NOT NULL  COMMENT '活动量';
ALTER TABLE gps.d_cust_dev_activate_stat_monthly2 modify totalCnt  bigint(21) DEFAULT 0 NULL  COMMENT '总计数';
ALTER TABLE gps.d_cust_dev_active_stat_daily modify activeDay  varchar(10)  NULL  COMMENT '活跃日';
ALTER TABLE gps.d_cust_dev_active_stat_daily modify activeCnt  bigint(21) DEFAULT 0 NOT NULL  COMMENT '活动量';
ALTER TABLE gps.d_cust_dev_active_stat_monthly modify activeMonth  varchar(7)  NULL  COMMENT '活动月';
ALTER TABLE gps.d_cust_dev_active_stat_monthly modify activeCnt  bigint(21) DEFAULT 0 NOT NULL  COMMENT '活动量';
ALTER TABLE gps.d_cust_dev_active_stat_monthly2 modify activeCnt  bigint(21) DEFAULT 0 NOT NULL  COMMENT '活动量';
ALTER TABLE gps.d_daily_record modify address  varchar(100)  NULL  COMMENT '地址';
ALTER TABLE gps.d_daily_record_201603 modify address  varchar(100)  NULL  COMMENT '地址';
ALTER TABLE gps.d_daoqiang_mileage_stat modify id  bigint(20)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_daoqiang_mileage_stat modify sn  bigint(20)  NULL  COMMENT '设备号';
ALTER TABLE gps.d_daoqiang_mileage_stat modify currentDate  date  NULL  COMMENT '当前的日期';
ALTER TABLE gps.d_daoqiang_mileage_stat modify lastReportDate  date  NULL  COMMENT '上次报告日期';
ALTER TABLE gps.d_daoqiang_mileage_stat modify todayMileage  double(20,2)  NULL  COMMENT '今天里程';
ALTER TABLE gps.d_daoqiang_mileage_stat modify totalMileage  double(20,2)  NULL  COMMENT '总里程';
ALTER TABLE gps.d_daoqiang_mileage_stat modify didiNo  bigint(20)  NULL  COMMENT '滴滴编号';
ALTER TABLE gps.d_daoqiang_mileage_stat modify vehicleId  varchar(32)  DEFAULT ''  COMMENT '车辆编号';
ALTER TABLE gps.d_daoqiang_mileage_stat_his modify id  bigint(20)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_daoqiang_mileage_stat_his modify sn  bigint(20)  NULL  COMMENT '设备号';
ALTER TABLE gps.d_daoqiang_mileage_stat_his modify currentDate  date  NULL  COMMENT '当前的日期';
ALTER TABLE gps.d_daoqiang_mileage_stat_his modify lastReportDate  date  NULL  COMMENT '上次报告日期';
ALTER TABLE gps.d_daoqiang_mileage_stat_his modify todayMileage  double(20,2)  NULL  COMMENT '今天里程';
ALTER TABLE gps.d_daoqiang_mileage_stat_his modify totalMileage  double(20,2)  NULL  COMMENT '总里程';
ALTER TABLE gps.d_daoqiang_mileage_stat_his modify didiNo  bigint(20)  NULL  COMMENT '滴滴编号';
ALTER TABLE gps.d_daoqiang_mileage_stat_his modify vehicleId  varchar(32)  DEFAULT ''  COMMENT '车辆编号';
ALTER TABLE gps.d_daoqiang_user modify id  bigint(20)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_daoqiang_user modify sn  bigint(20)  NULL  COMMENT '设备号';
ALTER TABLE gps.d_daoqiang_user modify didiNo  bigint(20)  NULL  COMMENT '滴滴编号';
ALTER TABLE gps.d_daoqiang_user modify activeDate  datetime  NULL  COMMENT '活动日期';
ALTER TABLE gps.d_daoqiang_user modify appType  int(11)  NOT NULL  COMMENT '应用类型';
ALTER TABLE gps.d_daoqiang_user modify state  int(11) DEFAULT 0 NOT NULL  COMMENT '状态';
ALTER TABLE gps.d_daoqiang_user modify deleteDate  datetime  NULL  COMMENT '删除日期';
ALTER TABLE gps.d_daoqiang_user modify updateTime  datetime  NULL  COMMENT '更新时间';
ALTER TABLE gps.d_daoqiang_user modify createTime  datetime  NULL  COMMENT '创建时间';
ALTER TABLE gps.d_daoqiang_user modify vehicleId  varchar(32)  DEFAULT ''  COMMENT '车辆编号';
ALTER TABLE gps.d_ddhd_collect modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_ddhd_log modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_ddhd_status modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_device_activate_detail_0118 modify id  int(11) DEFAULT 0 NOT NULL  COMMENT '主键';
ALTER TABLE gps.d_device_activate_detail_0118 modify sn  varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL  COMMENT '设备号';
ALTER TABLE gps.d_device_activate_detail_0118 modify vehicleId  int(11) DEFAULT 0 NULL  COMMENT '车辆编号';
ALTER TABLE gps.d_device_activate_detail_0118 modify sim  varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL  COMMENT '模拟';
ALTER TABLE gps.d_device_activate_detail_0118 modify activeDate  datetime  NULL  COMMENT '活动日期';
ALTER TABLE gps.d_device_activate_detail_0118 modify createTime  datetime  NULL  COMMENT '创建时间';
ALTER TABLE gps.d_device_activate_detail_202101_04 modify id  int(11) DEFAULT 0 NOT NULL  COMMENT '主键';
ALTER TABLE gps.d_device_activate_detail_202101_04 modify sn  varchar(20)  NULL  COMMENT '设备号';
ALTER TABLE gps.d_device_activate_detail_202101_04 modify vehicleId  int(11) DEFAULT 0 NULL  COMMENT '车辆编号';
ALTER TABLE gps.d_device_activate_detail_202101_04 modify sim  varchar(20)  NULL  COMMENT '模拟';
ALTER TABLE gps.d_device_activate_detail_202101_04 modify activeDate  datetime  NULL  COMMENT '活动日期';
ALTER TABLE gps.d_device_activate_detail_bak modify id  int(11) DEFAULT 0 NOT NULL  COMMENT '主键';
ALTER TABLE gps.d_device_activate_detail_bak modify sn  varchar(20)  NULL  COMMENT '设备号';
ALTER TABLE gps.d_device_activate_detail_bak modify vehicleId  int(11) DEFAULT 0 NULL  COMMENT '车辆编号';
ALTER TABLE gps.d_device_activate_detail_bak modify sim  varchar(20)  NULL  COMMENT '模拟';
ALTER TABLE gps.d_device_activate_detail_bak modify activeDate  datetime  NULL  COMMENT '活动日期';
ALTER TABLE gps.d_device_activate_detail_bak modify createTime  datetime  NULL  COMMENT '创建时间';
ALTER TABLE gps.d_device_active_detail modify id  int(11) DEFAULT 0 NOT NULL  COMMENT '主键';
ALTER TABLE gps.d_device_active_detail modify vehicleId  int(11) DEFAULT 0 NULL  COMMENT '车辆编号';
ALTER TABLE gps.d_device_active_detail modify sn  varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL  COMMENT '设备号';
ALTER TABLE gps.d_device_delivery_detail modify order_code  varchar(32)  NULL  COMMENT '订购代码';
ALTER TABLE gps.d_device_delivery_detail modify attrib_code  varchar(32)  NULL  COMMENT '属性码';
ALTER TABLE gps.d_device_delivery_detail modify sn  varchar(32)  NULL  COMMENT '设备号';
ALTER TABLE gps.d_device_delivery_detail modify sim  varchar(32)  NULL  COMMENT '模拟';
ALTER TABLE gps.d_device_delivery_detail modify iccid  varchar(32)  NULL  COMMENT 'icc主键';
ALTER TABLE gps.d_device_delivery_detail modify batch_no  varchar(32)  NULL  COMMENT '批号';
ALTER TABLE gps.d_device_delivery_detail modify send_merchant_no  varchar(32)  NULL  COMMENT '发送商户号';
ALTER TABLE gps.d_device_delivery_detail modify send_merchant_name  varchar(100)  NULL  COMMENT '发送商户名称';
ALTER TABLE gps.d_device_delivery_detail modify send_date  varchar(32)  NULL  COMMENT '发送日期';
ALTER TABLE gps.d_device_delivery_detail modify send_date2  datetime  NULL  COMMENT '发送日期2';
ALTER TABLE gps.d_device_freq modify operation_id  varchar(100)  NULL  COMMENT '操作编号';
ALTER TABLE gps.d_device_freq_yang modify operation_id  varchar(100)  NULL  COMMENT '操作编号';
ALTER TABLE gps.d_device_import_log modify id  bigint(10)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_device_import_log_detail modify id  int(10)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_device_import_log_detail modify import_log_id  int(10)  NULL  COMMENT '导入日志主键';
ALTER TABLE gps.d_device_offline_ratio modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_device_offline_ratio modify login_user_id  int(10)  NULL  COMMENT '登录用户名';
ALTER TABLE gps.d_device_offline_ratio modify create_time  datetime  NULL  COMMENT '创造时间';
ALTER TABLE gps.d_device_offline_ratio modify update_time  datetime  NULL  COMMENT '更新时间';
ALTER TABLE gps.d_device_operate_log modify id  double   auto_increment COMMENT '主键';
ALTER TABLE gps.d_device_operate_log modify sn  varchar(60)  NULL  COMMENT '设备号';
ALTER TABLE gps.d_device_operate_log modify standno  varchar(150)  NULL  COMMENT '站号';
ALTER TABLE gps.d_device_operate_log modify name  varchar(600)  NULL  COMMENT '姓名';
ALTER TABLE gps.d_device_operate_log modify operateAction  varchar(300)  NULL  COMMENT '操作动作';
ALTER TABLE gps.d_device_operate_log modify operateFunction  varchar(300)  NULL  COMMENT '操作函数';
ALTER TABLE gps.d_device_operate_log modify operateUserId  double  NULL  COMMENT '操作用户主键';
ALTER TABLE gps.d_device_operate_log modify operateTime  datetime  NULL  COMMENT '操作时间';
ALTER TABLE gps.d_device_operate_log modify vehicleId  double  NULL  COMMENT '车辆编号';
ALTER TABLE gps.d_device_separate_alarm modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_device_stat_active modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_device_stat_mileage modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_device_status modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_didi_ensure_plan_temp modify trackerId  int(11) DEFAULT 0 NOT NULL  COMMENT 'tracker主键';
ALTER TABLE gps.d_didi_ensure_plan_temp modify vehicleId  int(11) DEFAULT 0 NULL  COMMENT '车辆编号';
ALTER TABLE gps.d_didi_ensure_plan_temp modify sn  varchar(20)  NULL  COMMENT '设备号';
ALTER TABLE gps.d_didi_ensure_plan_temp modify sim  varchar(20)  NULL  COMMENT '模拟';
ALTER TABLE gps.d_didi_ensure_plan_temp modify activeDate  datetime  NULL  COMMENT '活动日期';
ALTER TABLE gps.d_electric_fence modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_electric_fence_alarm modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_electric_fence_alarm modify updateTime  datetime  NULL  COMMENT '更新时间';
ALTER TABLE gps.d_electric_fence_alarm modify createTime  datetime  NULL  COMMENT '创建时间';
ALTER TABLE gps.d_electric_fence_alarm_temp modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_electric_fence_alarm_temp modify updateTime  datetime  NULL  COMMENT '更新时间';
ALTER TABLE gps.d_electric_fence_alarm_temp modify createTime  datetime  NULL  COMMENT '创建时间';
ALTER TABLE gps.d_electric_fence_drive modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_electric_fence_sns modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_function modify createtime  datetime  NULL  COMMENT '创建时间';
ALTER TABLE gps.d_function modify url  varchar(100)  NULL  COMMENT '网址';
ALTER TABLE gps.d_function modify type  int(1)  NULL  COMMENT '类型';
ALTER TABLE gps.d_fund_account modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_gh_devicetime modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_gh_devicetime modify workOrderNo  varchar(50)  NULL  COMMENT '工单号';
ALTER TABLE gps.d_gh_devicetime modify name  varchar(50)  NULL  COMMENT '姓名';
ALTER TABLE gps.d_gh_devicetime modify area  varchar(50)  NULL  COMMENT '区域';
ALTER TABLE gps.d_gh_devicetime modify company  varchar(50)  NULL  COMMENT '公司';
ALTER TABLE gps.d_gh_devicetime modify sqbh1  varchar(50)  NULL  COMMENT 'sqbh1';
ALTER TABLE gps.d_gh_devicetime modify sn  varchar(20)  NULL  COMMENT '设备号';
ALTER TABLE gps.d_gh_devicetime modify standno  varchar(50)  NULL  COMMENT '站号';
ALTER TABLE gps.d_gh_devicetime modify commissionDate  datetime  NULL  COMMENT '委托日期';
ALTER TABLE gps.d_gh_devicetime modify status  varchar(20)  NULL  COMMENT '地位';
ALTER TABLE gps.d_gh_devicetime modify location  varchar(20)  NULL  COMMENT '地点';
ALTER TABLE gps.d_gh_devicetime modify type  varchar(10)  NULL  COMMENT '类型';
ALTER TABLE gps.d_gh_devicetime modify gpsTime  varchar(15)  NULL  COMMENT '全球定位系统时间';
ALTER TABLE gps.d_gh_devicetime modify gprsTime  varchar(15)  NULL  COMMENT 'gprs时间';
ALTER TABLE gps.d_gh_devicetime modify subGpsTime  varchar(15)  NULL  COMMENT 'subGpsTime';
ALTER TABLE gps.d_gh_devicetime modify subGprsTime  varchar(15)  NULL  COMMENT 'subGprsTime';
ALTER TABLE gps.d_gh_devicetime modify importDate  datetime  NULL  COMMENT '进口日期';
ALTER TABLE gps.d_gps_config modify d_gpsconfig_id  int(11)   auto_increment COMMENT 'gpsconfig 主键';
ALTER TABLE gps.d_gps_config modify typeNo  varchar(20)  NULL  COMMENT '类型No';
ALTER TABLE gps.d_gps_config modify typeVal  varchar(200)  NULL  COMMENT '类型值';
ALTER TABLE gps.d_gps_config modify remark  varchar(50)  NULL  COMMENT '评论';
ALTER TABLE gps.d_gps_config modify status  int(11) DEFAULT 0 NULL  COMMENT '地位';
ALTER TABLE gps.d_gps_rt_track modify ID  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_gqwind_report_alarm modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_gqwind_report_basis modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_gqwind_report_basis_extend modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_guanghui_mileage_stat modify id  bigint(20)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_guanghui_mileage_stat modify sn  bigint(20)  NULL  COMMENT '设备号';
ALTER TABLE gps.d_guanghui_mileage_stat modify currentDate  date  NULL  COMMENT '当前的日期';
ALTER TABLE gps.d_guanghui_mileage_stat modify lastReportDate  date  NULL  COMMENT '上次报告日期';
ALTER TABLE gps.d_guanghui_mileage_stat modify todayMileage  double(20,2)  NULL  COMMENT '今天里程';
ALTER TABLE gps.d_guanghui_mileage_stat modify totalMileage  double(20,2)  NULL  COMMENT '总里程';
ALTER TABLE gps.d_home_address modify addressId  int(11)   auto_increment COMMENT '地址标识';
ALTER TABLE gps.d_home_address modify vehicleId  int(11)  NULL  COMMENT '车辆编号';
ALTER TABLE gps.d_home_address modify acquireflag  int(1)  NULL  COMMENT '获取标志';
ALTER TABLE gps.d_home_address modify homeaddress  varchar(300)  NULL  COMMENT '家庭地址';
ALTER TABLE gps.d_home_address modify homeaddresslongi  varchar(48)  NULL  COMMENT '家庭地址longi';
ALTER TABLE gps.d_home_address modify homeaddresslat  varchar(48)  NULL  COMMENT '家庭地址lat';
ALTER TABLE gps.d_home_address modify createtime  datetime  NULL  COMMENT '创建时间';
ALTER TABLE gps.d_home_address modify updatetime  datetime  NULL  COMMENT '更新时间';
ALTER TABLE gps.d_home_address modify status  int(11) DEFAULT 0 NULL  COMMENT '地位';
ALTER TABLE gps.d_homeoffset_alarm modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_htfz_payment modify confirmTime  datetime  NULL  COMMENT '确认时间';
ALTER TABLE gps.d_interface_error_log modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_ivr_alarm_log modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_mail_send_queue modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_mb_rt_track modify ID  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_monitor_track modify trackerId  int(11)   auto_increment COMMENT 'tracker主键';
ALTER TABLE gps.d_pingan_vehicle_settle_request modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_power_off_alarm modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_power_off_alarm_temp modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_province modify id  bigint(20)  NULL  COMMENT '主键';
ALTER TABLE gps.d_province modify code  tinytext  NULL  COMMENT '代码';
ALTER TABLE gps.d_province modify name  tinytext  NULL  COMMENT '姓名';
ALTER TABLE gps.d_province modify enable_status  int(11)  NULL  COMMENT '启用状态';
ALTER TABLE gps.d_province modify del_flag  int(11)  NULL  COMMENT '德尔旗';
ALTER TABLE gps.d_province modify created_date  timestamp  NULL  COMMENT '创建日期';
ALTER TABLE gps.d_province modify created_by  int(11)  NULL  COMMENT '由...制作';
ALTER TABLE gps.d_province modify updated_date  timestamp  NULL  COMMENT '更新日期';
ALTER TABLE gps.d_province modify updated_by  int(11)  NULL  COMMENT '更新者';
ALTER TABLE gps.d_resident_alarm modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_resident_alarm_bak modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_resident_channel modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_resident_channel modify activeDate  datetime  NULL  COMMENT '活动日期';
ALTER TABLE gps.d_resident_channel modify beginTime  datetime  NULL  COMMENT '开始时间';
ALTER TABLE gps.d_resident_channel modify endTime  datetime  NULL  COMMENT '时间结束';
ALTER TABLE gps.d_resident_channel modify monthResident1  varchar(1000)  NULL  COMMENT '月居民1';
ALTER TABLE gps.d_resident_channel modify monthResident2  varchar(1000)  NULL  COMMENT '月居民2';
ALTER TABLE gps.d_resident_channel modify monthResident3  varchar(1000)  NULL  COMMENT '月居民3';
ALTER TABLE gps.d_resident_channel modify monthResident4  varchar(1000)  NULL  COMMENT '月居民4';
ALTER TABLE gps.d_resident_channel modify monthResident5  varchar(1000)  NULL  COMMENT '月居民5';
ALTER TABLE gps.d_resident_channel modify monthResident6  varchar(1000)  NULL  COMMENT '月居民6';
ALTER TABLE gps.d_resident_channel modify pushStatus  int(11) DEFAULT 0 NULL  COMMENT '推送状态';
ALTER TABLE gps.d_resident_custom modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_resident_custom modify beginTime  datetime  NULL  COMMENT '开始时间';
ALTER TABLE gps.d_resident_custom modify endTime  datetime  NULL  COMMENT '时间结束';
ALTER TABLE gps.d_resident_custom modify activateDate  datetime  NULL  COMMENT '激活日期';
ALTER TABLE gps.d_resident_custom_bak modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_resident_custom_bak modify beginTime  datetime  NULL  COMMENT '开始时间';
ALTER TABLE gps.d_resident_custom_bak modify endTime  datetime  NULL  COMMENT '时间结束';
ALTER TABLE gps.d_resident_custom_bak modify activateDate  datetime  NULL  COMMENT '激活日期';
ALTER TABLE gps.d_resident_cycle modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_resident_cycle modify beginTime  datetime  NULL  COMMENT '开始时间';
ALTER TABLE gps.d_resident_cycle modify endTime  datetime  NULL  COMMENT '时间结束';
ALTER TABLE gps.d_role modify autoClassfiyConfig  int(11) DEFAULT 1 NULL  COMMENT '自动分类配置';
ALTER TABLE gps.d_role_eshield_workorder modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_role_eshield_workorder modify createtime  datetime  NULL  COMMENT '创建时间';
ALTER TABLE gps.d_role_eshield_workorder modify roleid  int(11)  NULL  COMMENT '角色主键';
ALTER TABLE gps.d_role_function modify function_id  varchar(15)  NOT NULL  COMMENT '功能编号';
ALTER TABLE gps.d_role_function modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_role_function_temp modify function_id  varchar(15)  NOT NULL  COMMENT '功能编号';
ALTER TABLE gps.d_role_function_temp modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_role_insurance modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_role_insurance modify special_permission  tinyint(1)  NULL  COMMENT '特许';
ALTER TABLE gps.d_role_vehicle_detail modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_role_vehicle_detail modify roleid  int(11)  NOT NULL  COMMENT '角色主键';
ALTER TABLE gps.d_role_vehicle_detail modify type  int(1)  NULL  COMMENT '类型';
ALTER TABLE gps.d_role_vehicle_detail modify detailId  int(11)  NULL  COMMENT '详细信息';
ALTER TABLE gps.d_role_vehicle_detail_temp modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_role_vehicle_detail_temp modify roleid  int(11)  NOT NULL  COMMENT '角色主键';
ALTER TABLE gps.d_role_vehicle_detail_temp modify type  int(1)  NULL  COMMENT '类型';
ALTER TABLE gps.d_role_vehicle_detail_temp modify detailId  int(11)  NULL  COMMENT '详细信息';
ALTER TABLE gps.d_role_vehicle_group modify typeVal  mediumtext  NULL  COMMENT '类型值';
ALTER TABLE gps.d_role_vehicle_group_temp modify typeVal  mediumtext  NULL  COMMENT '类型值';
ALTER TABLE gps.d_send_config modify sendConfig_id  int(11)   auto_increment COMMENT '发送配置 主键';
ALTER TABLE gps.d_send_config modify area  varchar(100)  NULL  COMMENT '区域';
ALTER TABLE gps.d_send_config modify shopName  varchar(200)  NULL  COMMENT '店铺名称';
ALTER TABLE gps.d_send_config modify address  varchar(200)  NULL  COMMENT '地址';
ALTER TABLE gps.d_send_config modify email  varchar(500)  NULL  COMMENT '电子邮件';
ALTER TABLE gps.d_send_config modify createtime  datetime  NULL  COMMENT '创建时间';
ALTER TABLE gps.d_send_config modify updatetime  datetime  NULL  COMMENT '更新时间';
ALTER TABLE gps.d_service modify serviceId  int(11)   auto_increment COMMENT '服务标识';
ALTER TABLE gps.d_service modify serviceName  varchar(20)  NULL  COMMENT '服务名称';
ALTER TABLE gps.d_service modify contactsName  varchar(20)  NULL  COMMENT '联系人姓名';
ALTER TABLE gps.d_service modify contactsPhone  varchar(20)  NULL  COMMENT '联系人电话';
ALTER TABLE gps.d_service modify createtime  datetime  NULL  COMMENT '创建时间';
ALTER TABLE gps.d_service modify updateTime  datetime  NULL  COMMENT '更新时间';
ALTER TABLE gps.d_set_frequency modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_settle modify settleId  int(11)   auto_increment COMMENT '解决主键';
ALTER TABLE gps.d_settle modify sn  varchar(50)  NULL  COMMENT '设备号';
ALTER TABLE gps.d_settle modify status  int(10)  NULL  COMMENT '地位';
ALTER TABLE gps.d_settle modify settletime  datetime  NULL  COMMENT '结算时间';
ALTER TABLE gps.d_settle_detail_lina modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_settle_relation_classcustomer modify class_id  int(11)  NULL  COMMENT '班级号';
ALTER TABLE gps.d_settle_relation_classcustomer modify group_id  int(11)  NULL  COMMENT '组号';
ALTER TABLE gps.d_settle_relation_classcustomer modify class_name  varchar(128)  NULL  COMMENT '班级名称';
ALTER TABLE gps.d_settle_relation_classcustomer modify group_name  varchar(128)  NULL  COMMENT '团队名字';
ALTER TABLE gps.d_settle_relation_classcustomer modify customer_name  varchar(128)  NULL  COMMENT '顾客姓名';
ALTER TABLE gps.d_sms_delivery_log modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_sms_workorder_delivery modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_special_promise_insurance modify spid  int(11)   auto_increment COMMENT '蜘蛛';
ALTER TABLE gps.d_special_promise_insurance modify specialType  varchar(100)  NULL  COMMENT '特殊类型';
ALTER TABLE gps.d_special_promise_insurance modify specialContent  varchar(700)  NULL  COMMENT '特殊内容';
ALTER TABLE gps.d_special_promise_insurance modify status  int(1) DEFAULT 0 NULL  COMMENT '地位';
ALTER TABLE gps.d_stat_alarm modify statId  int(11)   auto_increment COMMENT 'stat主键';
ALTER TABLE gps.d_stat_alarm_his modify statId  int(11)   auto_increment COMMENT 'stat主键';
ALTER TABLE gps.d_statistics_gps_count modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_sub_voltage modify id  int(10)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_sub_voltage modify sn  varchar(50)  NULL  COMMENT '设备号';
ALTER TABLE gps.d_sub_voltage modify voltage  double  NULL  COMMENT '电压';
ALTER TABLE gps.d_sub_voltage modify createtime  datetime  NULL  COMMENT '创建时间';
ALTER TABLE gps.d_sub_voltage modify updatetime  datetime  NULL  COMMENT '更新时间';
ALTER TABLE gps.d_task_report_file_upload modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_task_sent_log modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_task_sent_log modify name  varchar(100)  NULL  COMMENT '姓名';
ALTER TABLE gps.d_task_sent_log modify vin  varchar(50)  NULL  COMMENT '车架号';
ALTER TABLE gps.d_task_sent_log modify sentTime  datetime  NULL  COMMENT '发送时间';
ALTER TABLE gps.d_task_sent_log modify createTime  datetime  NULL  COMMENT '创建时间';
ALTER TABLE gps.d_task_sent_log modify updateTime  datetime  NULL  COMMENT '更新时间';
ALTER TABLE gps.d_test_drive_shop modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_test_drive_shop_route modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_track_alarm_rec modify alarmid  int(11)   auto_increment COMMENT '惊慌失措';
ALTER TABLE gps.d_track_alarm_rec modify updateTime  timestamp DEFAULT CURRENT_TIMESTAMP NULL on update CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE gps.d_track_alarm_rec_dailystat modify alarmDay  varchar(10)  NULL  COMMENT '报警日';
ALTER TABLE gps.d_track_alarm_rec_dailystat modify alarmCnt  bigint(21) DEFAULT 0 NOT NULL  COMMENT '报警次数';
ALTER TABLE gps.d_track_alarm_rec_dailystat_tmp modify alarmDay  varchar(10)  NULL  COMMENT '报警日';
ALTER TABLE gps.d_track_alarm_rec_dailystat_tmp6 modify sn  varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL  COMMENT '设备号';
ALTER TABLE gps.d_track_alarm_rec_dailystat_tmp6 modify alarmDay  varchar(10)  NULL  COMMENT '报警日';
ALTER TABLE gps.d_track_alarm_rec_history modify alarmid  int(11)   auto_increment COMMENT '惊慌失措';
ALTER TABLE gps.d_track_alarm_rec_history modify sn  varchar(30)  NULL  COMMENT '设备号';
ALTER TABLE gps.d_track_alarm_rec_history modify begintime  datetime  NULL  COMMENT '开始时间';
ALTER TABLE gps.d_track_alarm_rec_history modify lng  varchar(20)  NULL  COMMENT '液化天然气';
ALTER TABLE gps.d_track_alarm_rec_history modify lat  varchar(20)  NULL  COMMENT '纬度';
ALTER TABLE gps.d_track_alarm_rec_history modify speed  varchar(20)  NULL  COMMENT '速度';
ALTER TABLE gps.d_track_alarm_rec_history modify direction  varchar(20)  NULL  COMMENT '方向';
ALTER TABLE gps.d_track_alarm_rec_history modify alarmType  int(11)  NULL  COMMENT '警报类型';
ALTER TABLE gps.d_track_alarm_rec_history modify cityname  varchar(100)  NULL  COMMENT '城市名';
ALTER TABLE gps.d_track_alarm_rec_history modify delflag  int(11)  NULL  COMMENT '德尔旗';
ALTER TABLE gps.d_track_alarm_rec_history modify userid  int(20)  NULL  COMMENT '用户身份';
ALTER TABLE gps.d_track_alarm_rec_history modify lasttime  datetime  NULL  COMMENT '上次';
ALTER TABLE gps.d_track_alarm_rec_history modify lastlng  varchar(20)  NULL  COMMENT '持久';
ALTER TABLE gps.d_track_alarm_rec_history modify lastlat  varchar(20)  NULL  COMMENT '最后拉';
ALTER TABLE gps.d_track_alarm_rec_history modify alarmNo  int(10)  NULL  COMMENT '报警无';
ALTER TABLE gps.d_track_alarm_rec_history_temp modify alarmid  int(11)   auto_increment COMMENT '惊慌失措';
ALTER TABLE gps.d_track_alarm_rec_history_temp modify sn  varchar(30)  NULL  COMMENT '设备号';
ALTER TABLE gps.d_track_alarm_rec_history_temp modify begintime  datetime  NULL  COMMENT '开始时间';
ALTER TABLE gps.d_track_alarm_rec_history_temp modify lng  varchar(20)  NULL  COMMENT '液化天然气';
ALTER TABLE gps.d_track_alarm_rec_history_temp modify lat  varchar(20)  NULL  COMMENT '纬度';
ALTER TABLE gps.d_track_alarm_rec_history_temp modify speed  varchar(20)  NULL  COMMENT '速度';
ALTER TABLE gps.d_track_alarm_rec_history_temp modify direction  varchar(20)  NULL  COMMENT '方向';
ALTER TABLE gps.d_track_alarm_rec_history_temp modify alarmType  int(11)  NULL  COMMENT '警报类型';
ALTER TABLE gps.d_track_alarm_rec_history_temp modify cityname  varchar(100)  NULL  COMMENT '城市名';
ALTER TABLE gps.d_track_alarm_rec_history_temp modify delflag  int(11)  NULL  COMMENT '德尔旗';
ALTER TABLE gps.d_track_alarm_rec_history_temp modify userid  int(20)  NULL  COMMENT '用户身份';
ALTER TABLE gps.d_track_alarm_rec_history_temp modify lasttime  datetime  NULL  COMMENT '上次';
ALTER TABLE gps.d_track_alarm_rec_history_temp modify lastlng  varchar(20)  NULL  COMMENT '持久';
ALTER TABLE gps.d_track_alarm_rec_history_temp modify lastlat  varchar(20)  NULL  COMMENT '最后拉';
ALTER TABLE gps.d_track_alarm_rec_history_temp modify alarmNo  int(10)  NULL  COMMENT '报警无';
ALTER TABLE gps.d_track_alarm_rec_temp modify alarmid  int(11)   auto_increment COMMENT '惊慌失措';
ALTER TABLE gps.d_track_alarm_rec_temp modify updateTime  timestamp DEFAULT CURRENT_TIMESTAMP NULL on update CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE gps.d_track_alarm_rec_yang modify alarmid  int(11)   auto_increment COMMENT '惊慌失措';
ALTER TABLE gps.d_track_alarm_rec_yang modify updateTime  timestamp DEFAULT CURRENT_TIMESTAMP NULL on update CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE gps.d_track_alarm_type modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_track_info modify trackerId  int(11)   auto_increment COMMENT 'tracker主键';
ALTER TABLE gps.d_track_info modify deviceType  int(11)  NULL  COMMENT '设备类型';
ALTER TABLE gps.d_track_info modify deviceNo  varchar(20)  NULL  COMMENT '设备编号';
ALTER TABLE gps.d_track_info modify sn  varchar(20)  NULL  COMMENT '设备号';
ALTER TABLE gps.d_track_info modify imsi  varchar(50)  NULL  COMMENT '即时通讯';
ALTER TABLE gps.d_track_info modify iccid  varchar(50)  NULL  COMMENT 'icc主键';
ALTER TABLE gps.d_track_info modify simPhone  varchar(20)  NULL  COMMENT '电话';
ALTER TABLE gps.d_track_info modify activeDate  datetime  NULL  COMMENT '活动日期';
ALTER TABLE gps.d_track_info modify checkCode  varchar(20)  NULL  COMMENT '校验码';
ALTER TABLE gps.d_track_info modify modelId  int(11)  NULL  COMMENT '型号主键';
ALTER TABLE gps.d_track_info modify userId  int(11)  NULL  COMMENT '用户身份';
ALTER TABLE gps.d_track_info modify createtime  datetime  NULL  COMMENT '创建时间';
ALTER TABLE gps.d_track_info modify updateTime  datetime  NULL  COMMENT '更新时间';
ALTER TABLE gps.d_track_info modify d_LoginUserId  int(11)  NULL  COMMENT '登录用户 主键';
ALTER TABLE gps.d_track_info_import modify trackerId  int(11)   auto_increment COMMENT 'tracker主键';
ALTER TABLE gps.d_track_info_import modify deviceType  int(11)  NULL  COMMENT '设备类型';
ALTER TABLE gps.d_track_info_import modify deviceNo  varchar(20)  NULL  COMMENT '设备编号';
ALTER TABLE gps.d_track_info_import modify sn  varchar(20)  NULL  COMMENT '设备号';
ALTER TABLE gps.d_track_info_import modify imsi  varchar(50)  NULL  COMMENT '即时通讯';
ALTER TABLE gps.d_track_info_import modify iccid  varchar(50)  NULL  COMMENT 'icc主键';
ALTER TABLE gps.d_track_info_import modify simPhone  varchar(20)  NULL  COMMENT '电话';
ALTER TABLE gps.d_track_info_import modify activeDate  datetime  NULL  COMMENT '活动日期';
ALTER TABLE gps.d_track_info_import modify checkCode  varchar(20)  NULL  COMMENT '校验码';
ALTER TABLE gps.d_track_info_import modify modelId  int(11)  NULL  COMMENT '型号主键';
ALTER TABLE gps.d_track_info_import modify userId  int(11)  NULL  COMMENT '用户身份';
ALTER TABLE gps.d_track_info_import modify createtime  datetime  NULL  COMMENT '创建时间';
ALTER TABLE gps.d_track_info_import modify updateTime  datetime  NULL  COMMENT '更新时间';
ALTER TABLE gps.d_track_info_import modify d_LoginUserId  int(11)  NULL  COMMENT '登录用户 主键';
ALTER TABLE gps.d_track_log modify address  varchar(100)  NULL  COMMENT '地址';
ALTER TABLE gps.d_use_log modify logId  int(11)   auto_increment COMMENT '日志主键';
ALTER TABLE gps.d_user_class_detailed modify d_user_class_id  int(11)   auto_increment COMMENT 'd 用户类 主键';
ALTER TABLE gps.d_user_group_detailed modify d_User_group_id  int(11)   auto_increment COMMENT 'd 用户组 主键';
ALTER TABLE gps.d_userid_key modify createTime  datetime  NULL  COMMENT '创建时间';
ALTER TABLE gps.d_vehicle modify vehicleId  int(11)   auto_increment COMMENT '车辆编号';
ALTER TABLE gps.d_vehicle_brand modify brandId  int(11)   auto_increment COMMENT '品牌标识';
ALTER TABLE gps.d_vehicle_brand modify brandName  varchar(20)  NULL  COMMENT '品牌';
ALTER TABLE gps.d_vehicle_brand_type modify vehicleTypeId  int(11)   auto_increment COMMENT '车辆类型 主键';
ALTER TABLE gps.d_vehicle_brand_type modify vehicleTypeName  varchar(64)  NULL  COMMENT '车辆类型名称';
ALTER TABLE gps.d_vehicle_brand_type modify vehicleBrandId  int(11)  NULL  COMMENT '车辆品牌 主键';
ALTER TABLE gps.d_vehicle_device modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_vehicle_device modify imsi  varchar(50)  NULL  COMMENT '即时通讯';
ALTER TABLE gps.d_vehicle_insurance modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_vehicle_insurance modify createTime  datetime  NULL  COMMENT '创建时间';
ALTER TABLE gps.d_vehicle_insurance modify updateTime  datetime  NULL  COMMENT '更新时间';
ALTER TABLE gps.d_vehicle_insurance modify specialContent  varchar(700)  NULL  COMMENT '特殊内容';
ALTER TABLE gps.d_vehicle_insurance modify spid  int(11)  NULL  COMMENT '蜘蛛';
ALTER TABLE gps.d_vehicle_insurance modify channel_source  varchar(30)  NULL  COMMENT '渠道来源';
ALTER TABLE gps.d_vehicle_log modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_vehicle_log modify vehicleId  int(11)  NULL  COMMENT '车辆编号';
ALTER TABLE gps.d_vehicle_log modify createTime  datetime  NULL  COMMENT '创建时间';
ALTER TABLE gps.d_vehicle_poi modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_vehicle_poi modify createTime  datetime  NULL  COMMENT '创建时间';
ALTER TABLE gps.d_vehicle_remark modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_vehicle_subuserid_is_0_to_update_null modify vehicleId  int(11) DEFAULT 0 NOT NULL  COMMENT '车辆编号';
ALTER TABLE gps.d_vehicle_workorder modify workOrderId  int(11)   auto_increment COMMENT '工单编号';
ALTER TABLE gps.d_vehicle_workorder modify insuranceFlag  tinyint(2)  NULL  COMMENT '保险标志';
ALTER TABLE gps.d_vehicle_workorder modify vehicle_type  varchar(32)  NULL  COMMENT '车辆类型';
ALTER TABLE gps.d_vehicle_workorder_cancel modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_vehicle_workorder_gh modify workOrderId  int(11)   auto_increment COMMENT '工单编号';
ALTER TABLE gps.d_vehicle_workorder_gh modify vorderid  varchar(50)  NULL  COMMENT 'vorder主键';
ALTER TABLE gps.d_vehicle_workorder_gh modify ghstatus  varchar(5)  NULL  COMMENT '状态';
ALTER TABLE gps.d_vehicle_workorder_gh modify delTime  datetime  NULL  COMMENT '删除时间';
ALTER TABLE gps.d_vehicle_workorder_rep modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_vehicle_workorder_rep modify content  varchar(2000)  NULL  COMMENT '内容';
ALTER TABLE gps.d_vehicle_workorder_rep modify title  varchar(100)  NULL  COMMENT '标题';
ALTER TABLE gps.d_vehicle_workorder_rep modify createtime  datetime  NULL  COMMENT '创建时间';
ALTER TABLE gps.d_vehicle_workorder_rep modify updatetime  datetime  NULL  COMMENT '更新时间';
ALTER TABLE gps.d_violation modify violationId  int(11)   auto_increment COMMENT '违规标识';
ALTER TABLE gps.d_violation modify content  varchar(100)  NULL  COMMENT '内容';
ALTER TABLE gps.d_violation modify userId  int(11)  NULL  COMMENT '用户身份';
ALTER TABLE gps.d_violation modify createtime  datetime  NULL  COMMENT '创建时间';
ALTER TABLE gps.d_violation modify serviceId  int(11)  NULL  COMMENT '服务标识';
ALTER TABLE gps.d_violation modify vehicleId  int(11)  NULL  COMMENT '车辆编号';
ALTER TABLE gps.d_voltage modify id  int(10)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_voltage modify sn  varchar(50)  NULL  COMMENT '设备号';
ALTER TABLE gps.d_voltage modify voltage  double  NULL  COMMENT '电压';
ALTER TABLE gps.d_voltage modify createtime  datetime  NULL  COMMENT '创建时间';
ALTER TABLE gps.d_workorder_dispatch modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_workorder_node modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_workorder_reassign modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_workorder_reassign modify workOrderInfo  varchar(500)  NULL  COMMENT '工单信息';
ALTER TABLE gps.d_workorder_reassign modify createtime  datetime  NULL  COMMENT '创建时间';
ALTER TABLE gps.d_workorder_reassign modify updatetime  datetime  NULL  COMMENT '更新时间';
ALTER TABLE gps.d_workorder_retransmission modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_workorder_retransmission modify createtime  datetime  NULL  COMMENT '创建时间';
ALTER TABLE gps.d_workorder_retransmission modify updatetime  datetime  NULL  COMMENT '更新时间';
ALTER TABLE gps.d_wx_login_user modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_xianfeng_mileage_stat modify id  bigint(20)   auto_increment COMMENT '主键';
ALTER TABLE gps.d_xianfeng_mileage_stat modify sn  bigint(20)  NULL  COMMENT '设备号';
ALTER TABLE gps.d_xianfeng_mileage_stat modify currentDate  date  NULL  COMMENT '当前的日期';
ALTER TABLE gps.d_xianfeng_mileage_stat modify lastReportDate  date  NULL  COMMENT '上次报告日期';
ALTER TABLE gps.d_xianfeng_mileage_stat modify todayMileage  double(20,2)  NULL  COMMENT '今天里程';
ALTER TABLE gps.d_xianfeng_mileage_stat modify totalMileage  double(20,2)  NULL  COMMENT '总里程';
ALTER TABLE gps.dsns modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.dsns modify parent_id  int(11)  NULL  COMMENT '父母身份证';
ALTER TABLE gps.dsns modify dsn  varchar(255)  NOT NULL  COMMENT 'dsn';
ALTER TABLE gps.eshield_alarm modify alarmId  int(11)   auto_increment COMMENT '报警标识';
ALTER TABLE gps.eshield_alarm modify createTime  datetime  NULL  COMMENT '创建时间';
ALTER TABLE gps.eshield_alarm_process_log modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.eshield_alarm_type modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.eshield_attention_ignore modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.eshield_device modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.eshield_device_alarm modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.eshield_device_alarm modify update_time  timestamp DEFAULT CURRENT_TIMESTAMP NULL on update CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE gps.eshield_device_alarm_deal modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.eshield_device_alarm_deal modify sn  varchar(100)  NULL  COMMENT '设备号';
ALTER TABLE gps.eshield_device_alarm_deal modify dealwith  varchar(400)  NULL  COMMENT '处理';
ALTER TABLE gps.eshield_device_alarm_rule modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.eshield_device_alarm_rule modify update_time  timestamp DEFAULT CURRENT_TIMESTAMP NULL on update CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE gps.eshield_device_alarm_temp modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.eshield_device_alarm_temp modify update_time  timestamp DEFAULT CURRENT_TIMESTAMP NULL on update CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE gps.eshield_device_classify modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.eshield_device_journeys modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.eshield_device_out_province_alarm modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.eshield_device_out_province_basis modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.eshield_device_overspeed modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.eshield_device_overspeed_copy modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.eshield_sys_log modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.flowmgn_business_settlement modify settlement_name  varchar(64)  NULL  COMMENT '定居点名称';
ALTER TABLE gps.gps_vehicle_settled modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.iot_card_excel modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.iot_card_excel modify sim  varchar(32)  NULL  COMMENT '模拟';
ALTER TABLE gps.iot_card_excel modify imsi  varchar(32)  NULL  COMMENT '即时通讯';
ALTER TABLE gps.iot_card_excel modify iccid  varchar(32)  NULL  COMMENT 'icc主键';
ALTER TABLE gps.iot_card_excel modify company_id  varchar(32)  NULL  COMMENT '公司编号';
ALTER TABLE gps.iot_card_excel modify sim_status  varchar(32)  NULL  COMMENT '模拟状态';
ALTER TABLE gps.iot_card_excel modify stop_reason  varchar(32)  NULL  COMMENT '停止原因';
ALTER TABLE gps.iot_card_excel modify active_date  date  NULL  COMMENT '有效日期';
ALTER TABLE gps.order_info_detail modify LOGISTICS_ID  int(11)  NULL  COMMENT '物流编号';
ALTER TABLE gps.province modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.province modify ProvinceName  varchar(40) CHARACTER SET utf8 COLLATE utf8_bin NULL  COMMENT '省名';
ALTER TABLE gps.qrtz_blob_triggers modify TRIGGER_NAME  varchar(200)  NOT NULL  COMMENT '触发器名称';
ALTER TABLE gps.qrtz_blob_triggers modify TRIGGER_GROUP  varchar(200)  NOT NULL  COMMENT '触发器组';
ALTER TABLE gps.qrtz_blob_triggers modify BLOB_DATA  blob  NULL  COMMENT '斑点数据';
ALTER TABLE gps.qrtz_calendars modify CALENDAR_NAME  varchar(200)  NOT NULL  COMMENT '日历名称';
ALTER TABLE gps.qrtz_calendars modify CALENDAR  blob  NOT NULL  COMMENT '日历';
ALTER TABLE gps.qrtz_cron_triggers modify TRIGGER_NAME  varchar(200)  NOT NULL  COMMENT '触发器名称';
ALTER TABLE gps.qrtz_cron_triggers modify TRIGGER_GROUP  varchar(200)  NOT NULL  COMMENT '触发器组';
ALTER TABLE gps.qrtz_cron_triggers modify CRON_EXPRESSION  varchar(200)  NOT NULL  COMMENT 'CRON 表达式';
ALTER TABLE gps.qrtz_cron_triggers modify TIME_ZONE_ID  varchar(80)  NULL  COMMENT '时区 主键';
ALTER TABLE gps.qrtz_fired_triggers modify ENTRY_ID  varchar(95)  NOT NULL  COMMENT '条目编号';
ALTER TABLE gps.qrtz_fired_triggers modify TRIGGER_NAME  varchar(200)  NOT NULL  COMMENT '触发器名称';
ALTER TABLE gps.qrtz_fired_triggers modify TRIGGER_GROUP  varchar(200)  NOT NULL  COMMENT '触发器组';
ALTER TABLE gps.qrtz_fired_triggers modify IS_VOLATILE  varchar(1)  NOT NULL  COMMENT '易变';
ALTER TABLE gps.qrtz_fired_triggers modify INSTANCE_NAME  varchar(200)  NOT NULL  COMMENT '实例名称';
ALTER TABLE gps.qrtz_fired_triggers modify FIRED_TIME  bigint(13)  NOT NULL  COMMENT '射击时间';
ALTER TABLE gps.qrtz_fired_triggers modify PRIORITY  int(11)  NOT NULL  COMMENT '优先';
ALTER TABLE gps.qrtz_fired_triggers modify STATE  varchar(16)  NOT NULL  COMMENT '状态';
ALTER TABLE gps.qrtz_fired_triggers modify JOB_NAME  varchar(200)  NULL  COMMENT '职位名称';
ALTER TABLE gps.qrtz_fired_triggers modify JOB_GROUP  varchar(200)  NULL  COMMENT '工作组';
ALTER TABLE gps.qrtz_fired_triggers modify IS_STATEFUL  varchar(1)  NULL  COMMENT '是有状态的';
ALTER TABLE gps.qrtz_fired_triggers modify REQUESTS_RECOVERY  varchar(1)  NULL  COMMENT '请求恢复';
ALTER TABLE gps.qrtz_job_details modify JOB_NAME  varchar(200)  NOT NULL  COMMENT '职位名称';
ALTER TABLE gps.qrtz_job_details modify JOB_GROUP  varchar(200)  NOT NULL  COMMENT '工作组';
ALTER TABLE gps.qrtz_job_details modify DESCRIPTION  varchar(250)  NULL  COMMENT '描述';
ALTER TABLE gps.qrtz_job_details modify JOB_CLASS_NAME  varchar(250)  NOT NULL  COMMENT '工作类别名称';
ALTER TABLE gps.qrtz_job_details modify IS_DURABLE  varchar(1)  NOT NULL  COMMENT '经久耐用';
ALTER TABLE gps.qrtz_job_details modify IS_VOLATILE  varchar(1)  NOT NULL  COMMENT '易变';
ALTER TABLE gps.qrtz_job_details modify IS_STATEFUL  varchar(1)  NOT NULL  COMMENT '是有状态的';
ALTER TABLE gps.qrtz_job_details modify REQUESTS_RECOVERY  varchar(1)  NOT NULL  COMMENT '请求恢复';
ALTER TABLE gps.qrtz_job_details modify JOB_DATA  blob  NULL  COMMENT '工作数据';
ALTER TABLE gps.qrtz_job_listeners modify JOB_NAME  varchar(200)  NOT NULL  COMMENT '职位名称';
ALTER TABLE gps.qrtz_job_listeners modify JOB_GROUP  varchar(200)  NOT NULL  COMMENT '工作组';
ALTER TABLE gps.qrtz_job_listeners modify JOB_LISTENER  varchar(200)  NOT NULL  COMMENT '工作听众';
ALTER TABLE gps.qrtz_locks modify LOCK_NAME  varchar(40)  NOT NULL  COMMENT '锁定名称';
ALTER TABLE gps.qrtz_paused_trigger_grps modify TRIGGER_GROUP  varchar(200)  NOT NULL  COMMENT '触发器组';
ALTER TABLE gps.qrtz_scheduler_state modify INSTANCE_NAME  varchar(200)  NOT NULL  COMMENT '实例名称';
ALTER TABLE gps.qrtz_scheduler_state modify LAST_CHECKIN_TIME  bigint(13)  NOT NULL  COMMENT '最后入住时间';
ALTER TABLE gps.qrtz_scheduler_state modify CHECKIN_INTERVAL  bigint(13)  NOT NULL  COMMENT '检查间隔';
ALTER TABLE gps.qrtz_simple_triggers modify TRIGGER_NAME  varchar(200)  NOT NULL  COMMENT '触发器名称';
ALTER TABLE gps.qrtz_simple_triggers modify TRIGGER_GROUP  varchar(200)  NOT NULL  COMMENT '触发器组';
ALTER TABLE gps.qrtz_simple_triggers modify REPEAT_COUNT  bigint(7)  NOT NULL  COMMENT '重复计数';
ALTER TABLE gps.qrtz_simple_triggers modify REPEAT_INTERVAL  bigint(12)  NOT NULL  COMMENT '重复间隔';
ALTER TABLE gps.qrtz_simple_triggers modify TIMES_TRIGGERED  bigint(10)  NOT NULL  COMMENT '触发时间';
ALTER TABLE gps.qrtz_trigger_listeners modify TRIGGER_NAME  varchar(200)  NOT NULL  COMMENT '触发器名称';
ALTER TABLE gps.qrtz_trigger_listeners modify TRIGGER_GROUP  varchar(200)  NOT NULL  COMMENT '触发器组';
ALTER TABLE gps.qrtz_trigger_listeners modify TRIGGER_LISTENER  varchar(200)  NOT NULL  COMMENT '触发器监听器';
ALTER TABLE gps.qrtz_triggers modify TRIGGER_NAME  varchar(200)  NOT NULL  COMMENT '触发器名称';
ALTER TABLE gps.qrtz_triggers modify TRIGGER_GROUP  varchar(200)  NOT NULL  COMMENT '触发器组';
ALTER TABLE gps.qrtz_triggers modify JOB_NAME  varchar(200)  NOT NULL  COMMENT '职位名称';
ALTER TABLE gps.qrtz_triggers modify JOB_GROUP  varchar(200)  NOT NULL  COMMENT '工作组';
ALTER TABLE gps.qrtz_triggers modify IS_VOLATILE  varchar(1)  NOT NULL  COMMENT '易变';
ALTER TABLE gps.qrtz_triggers modify DESCRIPTION  varchar(250)  NULL  COMMENT '描述';
ALTER TABLE gps.qrtz_triggers modify NEXT_FIRE_TIME  bigint(13)  NULL  COMMENT '下一次火灾时间';
ALTER TABLE gps.qrtz_triggers modify PREV_FIRE_TIME  bigint(13)  NULL  COMMENT '上一个火灾时间';
ALTER TABLE gps.qrtz_triggers modify PRIORITY  int(11)  NULL  COMMENT '优先';
ALTER TABLE gps.qrtz_triggers modify TRIGGER_STATE  varchar(16)  NOT NULL  COMMENT '触发状态';
ALTER TABLE gps.qrtz_triggers modify TRIGGER_TYPE  varchar(8)  NOT NULL  COMMENT '触发器类型';
ALTER TABLE gps.qrtz_triggers modify START_TIME  bigint(13)  NOT NULL  COMMENT '开始时间';
ALTER TABLE gps.qrtz_triggers modify END_TIME  bigint(13)  NULL  COMMENT '时间结束';
ALTER TABLE gps.qrtz_triggers modify CALENDAR_NAME  varchar(200)  NULL  COMMENT '日历名称';
ALTER TABLE gps.qrtz_triggers modify MISFIRE_INSTR  smallint(2)  NULL  COMMENT '失火指令';
ALTER TABLE gps.qrtz_triggers modify JOB_DATA  blob  NULL  COMMENT '工作数据';
ALTER TABLE gps.t_nbfl_vehicle modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.t_nbfl_vehicle modify shop_name  varchar(32)  NULL  COMMENT '店铺名称';
ALTER TABLE gps.t_nbfl_vehicle modify order_sn  varchar(32)  NULL  COMMENT '序号';
ALTER TABLE gps.t_nbfl_vehicle modify name  varchar(32)  NULL  COMMENT '姓名';
ALTER TABLE gps.t_nbfl_vehicle modify vin  varchar(32)  NULL  COMMENT '车架号';
ALTER TABLE gps.t_nbfl_vehicle modify sn  varchar(32)  NULL  COMMENT '设备号';
ALTER TABLE gps.t_nbfl_vehicle modify dev_type  varchar(32)  NULL  COMMENT '开发类型';
ALTER TABLE gps.t_nbfl_vehicle modify active_time  datetime  NULL  COMMENT '活动时间';
ALTER TABLE gps.t_nbfl_vehicle modify license_plate  varchar(32)  NULL  COMMENT '牌照';
ALTER TABLE gps.t_nbfl_vehicle modify status  varchar(32)  NULL  COMMENT '地位';
ALTER TABLE gps.t_nbfl_vehicle modify licensed_city  varchar(32)  NULL  COMMENT '持牌城市';
ALTER TABLE gps.t_track_stujudge_alarm modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.t_track_stujudge_alarm_yang modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE gps.wx_user modify id  int(11)   auto_increment COMMENT '主键';
