alter table neshield.base_cities comment '城市基础数据表';
alter table neshield.base_provinces comment '省份基础数据表';
alter table neshield.base_zone comment '县区基础数据表';
alter table neshield.d_app_image comment '工单图片迁移表';
alter table neshield.t_bigdata_fencemember comment '大数据围栏设备临时表';
alter table neshield.t_device_freq comment '设备调频表';
alter table neshield.t_device_temp_model comment '设备型号临时表';
alter table neshield.t_electric_fence comment '电子围栏表';
alter table neshield.t_electric_fence_sns comment '电子围栏设备表';
alter table neshield.t_menu comment '菜单表';
alter table neshield.t_test_drive_shop comment '试驾门店表';
alter table neshield.t_test_drive_shop_route comment '试驾线路表';
alter table neshield.t_vehicle_model comment '车辆型号表';
alter table neshield.t_zhongli_account comment '仲利账号迁移表';
alter table neshield.t_zhongli_department comment '仲利部门迁移表';
alter table neshield.t_zhongli_vehicle comment '仲利车辆迁移表';
alter table neshield.t_zhongli_vehicle0523 comment '仲利车辆迁移表0523';
alter table neshield.vehicle_level_account comment '车辆账号对应层级表';
ALTER TABLE neshield.base_cities modify id  bigint(20)   auto_increment COMMENT '主键';
ALTER TABLE neshield.base_cities modify code  varchar(255)  NULL  COMMENT '城市code';
ALTER TABLE neshield.base_cities modify name  varchar(255)  NULL  COMMENT '城市名称';
ALTER TABLE neshield.base_cities modify prov_code  varchar(255)  NULL  COMMENT '省份code';
ALTER TABLE neshield.base_provinces modify id  bigint(20)   auto_increment COMMENT '主键';
ALTER TABLE neshield.base_provinces modify code  varchar(255)  NULL  COMMENT '省份code';
ALTER TABLE neshield.base_provinces modify name  varchar(255)  NULL  COMMENT '省份名称';
ALTER TABLE neshield.base_provinces modify region_code  varchar(255)  NULL  COMMENT '大区code';
ALTER TABLE neshield.base_provinces modify region_name  varchar(255)  NULL  COMMENT '大区名称';
ALTER TABLE neshield.base_zone modify id  bigint(20)   auto_increment COMMENT '主键';
ALTER TABLE neshield.base_zone modify city_code  varchar(255)  NULL  COMMENT '城市code';
ALTER TABLE neshield.base_zone modify code  varchar(255)  NULL  COMMENT '县区code';
ALTER TABLE neshield.base_zone modify name  varchar(255)  NULL  COMMENT '县区名称';
ALTER TABLE neshield.base_zone modify prov_code  varchar(255)  NULL  COMMENT '省份code';
ALTER TABLE neshield.d_app_image modify name  varchar(50)  NULL  COMMENT '图片名称';
ALTER TABLE neshield.t_alarm_electric_fence modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_alarm_track_rec modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_alarm_track_stujudge modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_alarm_warn_alarm_type modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_alarm_warn_analyse modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_alarm_warn_analyse_process modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_approval modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_approval_history modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_bigdata_fencemember modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_bigdata_fencemember modify fence_id  int(11)  NULL  COMMENT '围栏主键';
ALTER TABLE neshield.t_bigdata_fencemember modify system_id  int(11)  NULL  COMMENT '子系统唯一id';
ALTER TABLE neshield.t_bigdata_fencemember modify sn  varchar(32)  NULL  COMMENT '设备号';
ALTER TABLE neshield.t_bigdata_fencemember modify device_type  int(11)  NULL  COMMENT '设备类型';
ALTER TABLE neshield.t_channel_risk_data modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_device modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_device_location modify sn  varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL  COMMENT '设备号';
ALTER TABLE neshield.t_device_speeding modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_device_speeding_history modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_device_temp_model modify sn  varchar(32)  NOT NULL  COMMENT '设备号';
ALTER TABLE neshield.t_device_temp_model modify name  varchar(32)  NULL  COMMENT '字典名称';
ALTER TABLE neshield.t_dict_data modify id  bigint(15)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_dict_data modify enable_status  int(2) DEFAULT 1 NULL  COMMENT '启用状态;1启用，2停用';
ALTER TABLE neshield.t_dict_data modify created_date  timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL  COMMENT '创建时间';
ALTER TABLE neshield.t_dict_type modify enable_status  int(2) DEFAULT 1 NULL  COMMENT '启用状态;1启用，2停用';
ALTER TABLE neshield.t_dict_type modify created_date  timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL  COMMENT '创建时间';
ALTER TABLE neshield.t_electric_fence modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_electric_fence modify edun_fence_id  int(11)  NULL  COMMENT '旧e盾围栏id';
ALTER TABLE neshield.t_electric_fence_copy modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_electric_fence_drive modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_electric_fence_drive_temp modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_electric_fence_sns modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_electric_fence_sns_copy modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_electric_instore_drive modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_electric_oil_mileage modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_fake_offline_change_frequently modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_fake_offline_fence_sn modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_fake_offline_vin modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_message_log modify id  bigint(20)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_message_log modify from_user  varchar(255)  NULL  COMMENT '发送人';
ALTER TABLE neshield.t_message_log modify to_user  varchar(255)  NULL  COMMENT '收件人';
ALTER TABLE neshield.t_message_log modify template  varchar(64)  NULL  COMMENT '模板标识';
ALTER TABLE neshield.t_message_log modify subject  varchar(255)  NULL  COMMENT '主题';
ALTER TABLE neshield.t_message_log modify content  varchar(1024)  NULL  COMMENT '内容';
ALTER TABLE neshield.t_message_log modify attachment  varchar(255)  NULL  COMMENT '附件';
ALTER TABLE neshield.t_message_log modify enable_status  int(2) DEFAULT 1 NULL  COMMENT '启用状态;1启用，2停用';
ALTER TABLE neshield.t_message_log modify del_flag  int(2) DEFAULT 0 NULL  COMMENT '删除标识：0正常，-1删除';
ALTER TABLE neshield.t_message_log modify created_date  timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL  COMMENT '创建时间';
ALTER TABLE neshield.t_message_log modify created_by  int(11)  NULL  COMMENT '创建人';
ALTER TABLE neshield.t_message_log modify updated_date  datetime  NULL  COMMENT '更新时间';
ALTER TABLE neshield.t_message_log modify updated_by  int(11)  NULL  COMMENT '更新人';
ALTER TABLE neshield.t_message_template modify id  bigint(20)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_message_template modify subject  varchar(255)  NULL  COMMENT '模板主题';
ALTER TABLE neshield.t_message_template modify enable_status  int(2) DEFAULT 1 NULL  COMMENT '启用状态;1启用，2停用';
ALTER TABLE neshield.t_message_template modify del_flag  int(2) DEFAULT 0 NULL  COMMENT '删除标识：0正常，-1删除';
ALTER TABLE neshield.t_message_template modify created_date  timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL  COMMENT '创建时间';
ALTER TABLE neshield.t_message_template modify created_by  int(11)  NULL  COMMENT '创建人';
ALTER TABLE neshield.t_message_template modify updated_date  datetime  NULL  COMMENT '更新时间';
ALTER TABLE neshield.t_message_template modify updated_by  int(11)  NULL  COMMENT '更新人';
ALTER TABLE neshield.t_statistics_fence_drive modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_statistics_instore_drive modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_tenant_vehicle_type modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_test_drive_shop modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_test_drive_shop_route modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_trial_drive_shop modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_trial_drive_vehicle modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_user modify email  varchar(150)  NULL  COMMENT '邮箱';
ALTER TABLE neshield.t_user_group modify id  int(11)  NOT NULL  COMMENT '主键';
ALTER TABLE neshield.t_vehicle modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_vehicle_device modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_vehicle_doc modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_vehicle_log modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_vehicle_model modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_vehicle_model modify vin  varchar(32)  NULL  COMMENT '车架号';
ALTER TABLE neshield.t_vehicle_model modify ownerName  varchar(32)  NULL  COMMENT '车主姓名';
ALTER TABLE neshield.t_vehicle_model modify classId  varchar(32)  NULL  COMMENT '分类主键';
ALTER TABLE neshield.t_vehicle_model modify modelId  varchar(32)  NULL  COMMENT '型号主键';
ALTER TABLE neshield.t_vehicle_model modify modelName  varchar(32)  NULL  COMMENT '型号名称';
ALTER TABLE neshield.t_vehicle_model modify activeTime  varchar(32)  NULL  COMMENT '激活时间';
ALTER TABLE neshield.t_whitelist_sn modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_workorder modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_workorder_documents modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_workorder_insurance modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_workorder_log modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_workorder_vehicle modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_workorder_vehicle_device modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_zhongli_carservice_info modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.t_zhongli_carservice_info modify order_no  varchar(64)  NULL  COMMENT '订单编号';
ALTER TABLE neshield.t_zhongli_carservice_info modify service_name  varchar(256)  NULL  COMMENT '服务商名称';
ALTER TABLE neshield.vehicle_level_account modify id  int(11)   auto_increment COMMENT '主键';
ALTER TABLE neshield.vehicle_level_account modify vin  varchar(32)  NULL  COMMENT '车架号';
ALTER TABLE neshield.vehicle_level_account modify account  varchar(20)  NULL  COMMENT '账号名称';
ALTER TABLE neshield.vehicle_level_account modify saccount  varchar(20)  NULL  COMMENT '账号名称';
